/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WitnessAnchorRegistry } from "./WitnessAnchorRegistry";
export * as factories from "./factories";
export { WitnessAnchorRegistry__factory } from "./factories/WitnessAnchorRegistry__factory";
