/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface WitnessAnchorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addWitness"
      | "anchor"
      | "authorizedWitnesses"
      | "batchCount"
      | "blockNumbers"
      | "getBatch"
      | "isWitness"
      | "owner"
      | "removeWitness"
      | "roots"
      | "timestamps"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Anchored" | "WitnessAdded" | "WitnessRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addWitness",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "anchor", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "authorizedWitnesses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blockNumbers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isWitness",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeWitness",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "roots", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "timestamps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "addWitness", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedWitnesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockNumbers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isWitness", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeWitness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roots", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timestamps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace AnchoredEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    root: BytesLike,
    timestamp: BigNumberish,
    blockNumber: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    root: string,
    timestamp: bigint,
    blockNumber: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    root: string;
    timestamp: bigint;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WitnessAddedEvent {
  export type InputTuple = [witness: AddressLike];
  export type OutputTuple = [witness: string];
  export interface OutputObject {
    witness: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WitnessRemovedEvent {
  export type InputTuple = [witness: AddressLike];
  export type OutputTuple = [witness: string];
  export interface OutputObject {
    witness: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WitnessAnchorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): WitnessAnchorRegistry;
  waitForDeployment(): Promise<this>;

  interface: WitnessAnchorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addWitness: TypedContractMethod<[witness: AddressLike], [void], "nonpayable">;

  anchor: TypedContractMethod<[merkleRoot: BytesLike], [bigint], "nonpayable">;

  authorizedWitnesses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchCount: TypedContractMethod<[], [bigint], "view">;

  blockNumbers: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getBatch: TypedContractMethod<
    [batchId: BigNumberish],
    [
      [string, bigint, bigint] & {
        root: string;
        timestamp: bigint;
        blockNum: bigint;
      }
    ],
    "view"
  >;

  isWitness: TypedContractMethod<[witness: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeWitness: TypedContractMethod<
    [witness: AddressLike],
    [void],
    "nonpayable"
  >;

  roots: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  timestamps: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  verify: TypedContractMethod<
    [batchId: BigNumberish, expectedRoot: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addWitness"
  ): TypedContractMethod<[witness: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<[merkleRoot: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedWitnesses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blockNumbers"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [batchId: BigNumberish],
    [
      [string, bigint, bigint] & {
        root: string;
        timestamp: bigint;
        blockNum: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isWitness"
  ): TypedContractMethod<[witness: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeWitness"
  ): TypedContractMethod<[witness: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roots"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "timestamps"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [batchId: BigNumberish, expectedRoot: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "Anchored"
  ): TypedContractEvent<
    AnchoredEvent.InputTuple,
    AnchoredEvent.OutputTuple,
    AnchoredEvent.OutputObject
  >;
  getEvent(
    key: "WitnessAdded"
  ): TypedContractEvent<
    WitnessAddedEvent.InputTuple,
    WitnessAddedEvent.OutputTuple,
    WitnessAddedEvent.OutputObject
  >;
  getEvent(
    key: "WitnessRemoved"
  ): TypedContractEvent<
    WitnessRemovedEvent.InputTuple,
    WitnessRemovedEvent.OutputTuple,
    WitnessRemovedEvent.OutputObject
  >;

  filters: {
    "Anchored(uint256,bytes32,uint256,uint256)": TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;
    Anchored: TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;

    "WitnessAdded(address)": TypedContractEvent<
      WitnessAddedEvent.InputTuple,
      WitnessAddedEvent.OutputTuple,
      WitnessAddedEvent.OutputObject
    >;
    WitnessAdded: TypedContractEvent<
      WitnessAddedEvent.InputTuple,
      WitnessAddedEvent.OutputTuple,
      WitnessAddedEvent.OutputObject
    >;

    "WitnessRemoved(address)": TypedContractEvent<
      WitnessRemovedEvent.InputTuple,
      WitnessRemovedEvent.OutputTuple,
      WitnessRemovedEvent.OutputObject
    >;
    WitnessRemoved: TypedContractEvent<
      WitnessRemovedEvent.InputTuple,
      WitnessRemovedEvent.OutputTuple,
      WitnessRemovedEvent.OutputObject
    >;
  };
}
