/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface WitnessAnchorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchor"
      | "batchCount"
      | "blockNumbers"
      | "getBatch"
      | "roots"
      | "timestamps"
      | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Anchored"): EventFragment;

  encodeFunctionData(functionFragment: "anchor", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "batchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blockNumbers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "roots", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "timestamps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batchCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockNumbers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roots", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timestamps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace AnchoredEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    root: BytesLike,
    timestamp: BigNumberish,
    blockNumber: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    root: string,
    timestamp: bigint,
    blockNumber: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    root: string;
    timestamp: bigint;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WitnessAnchorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): WitnessAnchorRegistry;
  waitForDeployment(): Promise<this>;

  interface: WitnessAnchorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchor: TypedContractMethod<[merkleRoot: BytesLike], [bigint], "nonpayable">;

  batchCount: TypedContractMethod<[], [bigint], "view">;

  blockNumbers: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getBatch: TypedContractMethod<
    [batchId: BigNumberish],
    [
      [string, bigint, bigint] & {
        root: string;
        timestamp: bigint;
        blockNum: bigint;
      }
    ],
    "view"
  >;

  roots: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  timestamps: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  verify: TypedContractMethod<
    [batchId: BigNumberish, expectedRoot: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<[merkleRoot: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "batchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blockNumbers"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [batchId: BigNumberish],
    [
      [string, bigint, bigint] & {
        root: string;
        timestamp: bigint;
        blockNum: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "roots"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "timestamps"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [batchId: BigNumberish, expectedRoot: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "Anchored"
  ): TypedContractEvent<
    AnchoredEvent.InputTuple,
    AnchoredEvent.OutputTuple,
    AnchoredEvent.OutputObject
  >;

  filters: {
    "Anchored(uint256,bytes32,uint256,uint256)": TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;
    Anchored: TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;
  };
}
